# from HigherOrderMeshingTri_Deprecated import HighOrderMeshTri, HighOrderMeshTri_UNSTABLE
# from HigherOrderMeshingTet_Depracated import HighOrderMeshTet, HighOrderMeshTet_UNSTABLE, HighOrderMeshTet_SEMISTABLE

from HigherOrderMeshingTri import HighOrderMeshTri_SEMISTABLE
from HigherOrderMeshingTet import HighOrderMeshTet_SEMISTABLE
from HigherOrderMeshingQuad import HighOrderMeshQuad